### ISSUE TITLE
[VSC] Ошибка при сохранении файла

### ISSUE THREAD

**Issue by ebugusey** [xDrivenDevelopment/1c-syntax#163]
VSC 1.0.0
language-1c-bsl-1.4.8

Когда я пытаюсь сохранить новый файл с выбранной подсветкой `1C (Query)` я получаю ошибку вот с таким вот стек-трейсом:
```
Cannot read property 'split' of null: TypeError: Cannot read property 'split' of null
    at Object.d [as join] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:22:12930)
    at t.suggestFileName (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:107:2318)
    at t.saveAs (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:107:1532)
    at t.doRun (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:102:23698)
    at t.run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:102:22444)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:86:9686
    at n.undefined.t.Class.define.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:23:24378)
    at p (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:86:9643)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:86:9374
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:57:18912
```

**Comment by nixel2007** [comment]
Версия vscode? версия пакета? куда пытаетесь сохранить?

**Comment by ebugusey** [comment]
Версию дописал в первом коменте. Просто нажимаю `Ctrl-S` или выбираю пункт меню и VCS выдает эту ошибку. Если сохранять как `Plain Text` то нормально идет, сразу появляется диалог сохранения.

**Comment by nixel2007** [comment]
Воспроизвел у себя.
Посмотрю, спасибо.

**Comment by nixel2007** [comment]
Исправлено.

Исправление появится в релизе 1.5
